all:
  children:
    routers:
      hosts:
        ROUTER:
          ansible_host: 192.168.122.10

    dist:
      hosts:
        DIST:
          ansible_host: 192.168.122.11
    access:
      hosts:
        ACCESS:
          ansible_host: 192.168.122.12
