---
- name: Create VLANs  switches
  hosts: dist,access
  gather_facts: no

  tasks:

    - name: create vlan
      ios_vlans:
        config:
          - vlan_id: "{{ item.id }}"
            name: "{{ item.name }}"
            state: active
        state: merged
      loop: "{{ vlans }}"
    - name: show vlan output
      ios_command:
        commands: show vlan brief
      register: vlans_brief

    - name: print output to screen
      debug:
        var: vlans_brief.stdout_lines
